location = /browse.php {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass unix:/tmp/php-cgi-82.sock;
    fastcgi_read_timeout 3600;
}

location / {
    try_files $uri $uri/ /index.php?$query_string;
}

rewrite ^/api/list$ /api/list.php last;
rewrite ^/api/zip$ /api/zip.php last;

location ^~ /tmp/ {
    types { application/zip zip; }
    add_header X-Content-Type-Options nosniff;
    add_header Cache-Control "private, max-age=3600";
}

location ~* \.(php|phtml)$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass unix:/tmp/php-cgi-82.sock;
    fastcgi_read_timeout 3600;
}

location ~ /\.(?!well-known).* {
    deny all;
}
